services:
  - type: web
    name: the-trader-server
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
